name: Dynamic-Selft-Service-Automation

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Check Python version
        run: python --version

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: powershell

      - name: Install Playwright Browsers
        run: playwright install
        shell: powershell

      - name: Create report directory
        run: |
          New-Item -ItemType Directory -Force -Path playwright-report
        shell: powershell

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings --capture=tee-sys --html=playwright-report/report.html --self-contained-html
        shell: powershell
        continue-on-error: true

      - name: Rerun failed tests (if any)
        if: ${{ failure() }}
        run: |
          pytest --disable-warnings -v
        shell: powershell

      - name: List report files
        run: |
          Get-ChildItem -Recurse playwright-report
        shell: powershell

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
